//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprigenok.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int AgentsID { get; set; }
        public System.DateTime Date { get; set; }
        public int NumberOfProduct { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Product Product { get; set; }
    }
}
